# Generated by Django 5.1.2 on 2024-11-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoloyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=200)),
                ('address', models.TextField()),
                ('salary', models.PositiveIntegerField()),
                ('emai_id', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('date_of_joning', models.DateField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='employee_image')),
            ],
        ),
    ]
