# Generated by Django 5.1.2 on 2024-11-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emoloyee',
            new_name='Employee',
        ),
    ]
